# Generated by Django 4.1 on 2023-03-27 18:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='register',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstname', models.CharField(max_length=100)),
                ('lastname', models.CharField(max_length=100)),
                ('username', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=100)),
                ('password1', models.CharField(max_length=100)),
                ('password2', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'register',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Uploads',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hse', models.ImageField(upload_to='Images/')),
                ('vhse', models.FileField(upload_to='Videos/')),
                ('htp', models.CharField(choices=[('RENT', 'rent'), ('BUY', 'buy')], max_length=10)),
                ('loc', models.CharField(max_length=100)),
                ('price', models.IntegerField()),
                ('desc', models.CharField(max_length=100)),
                ('web', models.CharField(max_length=100)),
                ('phone', models.IntegerField()),
            ],
            options={
                'db_table': 'upload',
                'managed': True,
            },
        ),
    ]
