# Generated by Django 4.1 on 2023-03-29 18:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('realtekrealty', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='home',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img', models.ImageField(upload_to='')),
                ('locate', models.CharField(max_length=100)),
                ('descr', models.CharField(max_length=100)),
                ('price', models.IntegerField()),
                ('call', models.IntegerField()),
            ],
            options={
                'db_table': 'loads',
                'managed': True,
            },
        ),
        migrations.RenameField(
            model_name='register',
            old_name='password1',
            new_name='password',
        ),
    ]
