# Generated by Django 4.1 on 2023-04-02 18:29

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('realtekrealty', '0002_home_rename_password1_register_password'),
    ]

    operations = [
        migrations.AddField(
            model_name='home',
            name='hse',
            field=models.ImageField(default=django.utils.timezone.now, upload_to='Home-Images/'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='register',
            name='firstname',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='register',
            name='lastname',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='uploads',
            name='hse',
            field=models.ImageField(default='some_value', upload_to='Images/'),
        ),
        migrations.AlterField(
            model_name='uploads',
            name='vhse',
            field=models.FileField(default='some_value', upload_to='Videos/'),
        ),
    ]
